# Generated by Django 6.0.1 on 2026-02-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100, verbose_name='Товары')),
                ('total', models.CharField(max_length=100, verbose_name='Итого')),
                ('name', models.CharField(max_length=100, verbose_name='Сумма заказ')),
                ('registration', models.CharField(max_length=150, verbose_name='Оформление')),
            ],
        ),
        migrations.CreateModel(
            name='Card_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img_suppliers/', verbose_name='Изображение')),
                ('visit', models.CharField(max_length=100, verbose_name='Типы')),
                ('name2', models.CharField(max_length=150, verbose_name='Информация')),
                ('text', models.TextField(verbose_name='Описание')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('name', models.CharField(max_length=100, verbose_name='Навание')),
                ('image2', models.ImageField(upload_to='img_suppliers/', verbose_name='Фото нравиться')),
                ('favourites', models.CharField(max_length=100, verbose_name='Избранное')),
                ('basket', models.CharField(max_length=100, verbose_name='В корзину')),
                ('favourites2', models.BooleanField(default=True)),
                ('basket2', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.TextField(verbose_name='Описание')),
                ('phone', models.CharField(max_length=150, verbose_name='Телефон номер')),
                ('mail', models.CharField(max_length=150, verbose_name='Почта')),
            ],
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Избранное')),
                ('image', models.ImageField(upload_to='img_suppliers/', verbose_name='Изображение')),
                ('name2', models.CharField(max_length=100, verbose_name='Название')),
                ('visit', models.CharField(max_length=100, verbose_name='Типы')),
                ('img', models.ImageField(upload_to='img_suppliers/', verbose_name='Фото нравиться')),
                ('bool1', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('phone', models.CharField(max_length=100, verbose_name='Номер телефон')),
                ('emile', models.EmailField(max_length=100, verbose_name='Электронная почта')),
                ('comment', models.TextField(verbose_name='Комментарий')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('organization', models.CharField(max_length=100, verbose_name='Наименование организации')),
                ('contact_person', models.CharField(max_length=100, verbose_name='Контактное лицо')),
                ('phone', models.CharField(max_length=100, verbose_name='Номер телефона')),
                ('emile', models.EmailField(blank=True, max_length=254, verbose_name='Emile')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=100, verbose_name='Улица')),
                ('house', models.CharField(max_length=100, verbose_name='Дом')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итого')),
            ],
        ),
        migrations.CreateModel(
            name='Product_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('name2', models.CharField(max_length=100, verbose_name='Одинатонные')),
                ('image', models.ImageField(upload_to='img_suppliers/', verbose_name='Изображение')),
                ('visit', models.JSONField(verbose_name='Размер')),
                ('have', models.PositiveIntegerField(verbose_name='Количество')),
                ('created_at', models.DateTimeField(verbose_name='Дата')),
                ('bool1', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('visit', models.CharField(max_length=200, verbose_name='Типы')),
                ('name2', models.CharField(max_length=100, verbose_name='месяц')),
                ('image', models.ImageField(upload_to='img_suppliers/', verbose_name='изображение')),
                ('bool1', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tovar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('visit', models.PositiveIntegerField(verbose_name='Размеры')),
                ('name2', models.CharField(max_length=100, verbose_name='Типы')),
                ('image', models.ImageField(upload_to='img_suppliers/', verbose_name='Нравиться фото')),
                ('bool1', models.BooleanField(default=True)),
            ],
        ),
    ]
